### ISSUE TITLE
virus detection

### ISSUE THREAD

**Issue by mohamadfg-dev** [Mysteriza/Browser-Password-Viewer#1]
hi bro , When I build the program, all antiviruses recognize it as a virus
How can I build without virus like the exe file that you put?

**Comment by Mysteriza** [comment]
it's a false positive, just ignore it. all antivirus detect this as a virus for sure because this program takes saved passwords from the browser. Try putting your project folder on the antivirus whitelist, or temporarily turning off your antivirus.
